DjangoMongoDBPortProject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [path('', include('GdzieTaKeja.urls')),
    path('admin/', admin.site.urls),
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

GdzieTaKeja/urls.py
from django.urls import path
from . import views

app_name = 'GdzieTaKeja'
urlpatterns = [
    path('', views.port_list, name="ports"),
    path('ports/', views.port_list, name='ports'),
    path('reservations/',views.reservation,name="reservation"),
    path('<str:port_id>/sectors/',views.sectors,name="sectors"),
    path('<str:port_id>/<str:sector_name>/<int:y_id>/slots/',views.slots,name="slots"),
    path('<str:port_id>/<str:sector_name>/<int:y_id>/<int:slot_id>/reserve',views.reserve,name="reserve"),
    path('<str:reservation_number>/', views.edit_reservation, name="edit_reservation")
    ]

GdzieTaKeja/models.py
from django.db import models

# Create your models here.

GdzieTaKeja/forms.py
from django import forms

types =(
    ("balastowy","balastowy"),
    ("mieczowy","mieczowy")
)
class CityForm(forms.Form):
    city = forms.CharField(label="Znajdź miasto",max_length=100,required=False)

class DimensionsForm(forms.Form):
    length = forms.FloatField(label="Podaj długość:")
    depth = forms.FloatField(label="Podaj zanurzenie:")
    width = forms.FloatField(label="Podaj szerokość:")
    type= forms.ChoiceField(label="Podaj typ:",choices=types)

class DataForm(forms.Form):
    yachtID=forms.CharField(label="Podaj numer rejestracyjny jachtu:",max_length=6,min_length=6)
    name=forms.CharField(label="Podaj imię:")
    surname=forms.CharField(label="Podaj nazwisko:")
    dateFrom=forms.DateField(label="Podaj początek rezerwacji(rrrr-mm-dd):")
    dateTo=forms.DateField(label="Podaj koniec rezerwacji(rrrr-mm-dd):")


class ReservationForm(forms.Form):
    reservationNumber = forms.CharField(label="Podaj numer rezerwacji:", min_length=6,max_length=6,required=True)

class EditReservationForm(forms.Form):
    dateFrom = forms.DateField(label="Początek rezerwacji(rrrr-mm-dd):")
    dateTo = forms.DateField(label="Koniec rezerwacji(rrrr-mm-dd):")

GdzieTaKeja/views.py
import string
import random

from bson import ObjectId
from datetime import datetime
from django.shortcuts import render, redirect

# Create your views here.
import pymongo
from .forms import CityForm,DimensionsForm,DataForm,ReservationForm,EditReservationForm

connection_string= 'mongodb+srv://mmikula:Marcinm17@cluster0.7q4lh.mongodb.net/PortDB?retryWrites=true&w=majority'
my_client = pymongo.MongoClient(connection_string)


dbname = my_client['PortDB']
ports = dbname["Port"]
reservations=dbname["Reservation"]
yachts=dbname["Yacht"]
dimensions = []
def get_res_number(length):
    letters = string.ascii_lowercase
    while True:
        resNum = ''.join(random.choice(letters) for _ in range(length))
        if len(list(reservations.find({'reservationNumber' : resNum}))) == 0:
            return resNum


def port_list(request):
    port_list = ports.find({})
    if request.method == 'POST':

        form = CityForm(request.POST)

        if form.is_valid():

            city=form.cleaned_data['city']
            port_list = ports.find({'name':{'$regex':city}})
            return render(request, 'GdzieTaKeja/ports.html',{'port_list': port_list, 'form': form})

    else:
        form = CityForm()
    return render(request, 'GdzieTaKeja/ports.html', {'port_list':port_list, 'form':form})


def sectors(request,port_id):
    portInstance=ObjectId(port_id)
    port = ports.find_one({'_id':portInstance})
    sectors_list=port["sectors"]
    filtered_sectors = []
    global dimensions
    if request.method == 'POST':

        form = DimensionsForm(request.POST)

        if form.is_valid():
            length=form.cleaned_data['length']
            depth = form.cleaned_data['depth']
            width = form.cleaned_data['width']
            y_type = form.cleaned_data['type']
            dimensions.append({'length':length,'depth':depth,'width':width,'y_type':y_type})
            y_data_id=len(dimensions)-1
            filtered_sectors=[]
            for s in sectors_list:
                if s['type'] == 'perpendicular':
                    q=0
                    for slot in s['slots']:
                        if slot['taken']==False:
                            q+=1
                    if q==0:
                        continue
                    req=0
                    if s['maxWidth'] >= width:
                        req+=1
                    if y_type == 'mieczowy':
                        req+=1
                    if y_type == 'balastowy':
                        if s['depth'] >= depth:
                            req+=1
                    if req==2:
                        filtered_sectors.append(s)
                else:
                    req=0
                    if y_type == 'mieczowy':
                        req+=1
                    if y_type == 'balastowy':
                        if s['depth'] >= depth:
                            req+=1
                    if s['availableLength'] >= length:
                        req+=1
                    if req==2:
                        filtered_sectors.append(s)
            return render(request, 'GdzieTaKeja/sectors.html',{'port_id':port_id,'y_id':y_data_id,'form':form,'filtered_sectors':filtered_sectors})

    else:
        form = DimensionsForm()
    return render(request, 'GdzieTaKeja/sectors.html',{'port_id':port_id,'form':form,'filtered_sectors':filtered_sectors})


def slots(request,port_id,y_id,sector_name):
    portInstance=ObjectId(port_id)
    port = ports.find_one({'_id':portInstance})
    sectors_list=port["sectors"]
    slot_list=''
    sector_type=''
    for s in sectors_list:
        if s['name']==sector_name:
            slot_list=[]
            for slot in s['slots']:
                if slot['taken'] == False:
                    slot_list.append(slot)
            sector_type=s['type']
    for slot in slot_list:
        slot['id']=int(slot['id'])
    return render(request, 'GdzieTaKeja/slots.html',{'slot_list':slot_list,'y_id':y_id,'port':port,'port_id':port_id,
                                                     'sector_name':sector_name,'sector_type':sector_type})


def reserve(request,port_id,sector_name,y_id,slot_id):
    portInstance = ObjectId(port_id)
    port = ports.find_one({'_id': portInstance})
    sectors_list = port["sectors"]

    sector_type = ''
    sector=None
    arrayid=-1
    global dimensions
    for i in range(len(sectors_list)):
        if sectors_list[i]['name'] == sector_name:
            sector_type = sectors_list[i]['type']
            sector=sectors_list[i]
            arrayid=i
    if sector_type=='parallel':
        if sector['availableLength']<dimensions[y_id]['length']:
            return render(request, 'GdzieTaKeja/results.html', {'action': 'reservation_unavailable'})
    if sector_type=='perpendicular':
        if sector['slots'][slot_id]['taken']==True:
            return render(request, 'GdzieTaKeja/results.html', {'action': 'reservation_unavailable'})
    if request.method == 'POST':

        form = DataForm(request.POST)

        if form.is_valid():
            yachtID=form.cleaned_data['yachtID']
            name=form.cleaned_data['name']
            surname=form.cleaned_data['surname']
            dateFrom=form.cleaned_data['dateFrom']
            dateTo=form.cleaned_data['dateTo']
            reservationNumber=get_res_number(6)
            yachts.insert_one({'in':yachtID,'depth':dimensions[y_id]['depth'],'length':dimensions[y_id]['length'],
                               'width':dimensions[y_id]['width'],'type':dimensions[y_id]['y_type']})
            if sector_type == 'parallel':
                newReservation={'reservationNumber':reservationNumber,'portID':port_id,'sectorID':sector_name,
                                'type':sector_type,'slot':None,
                                'ownerName':name,'ownerSurname':surname,'yachtID':yachtID,
                                'dateFrom':datetime.combine(dateFrom, datetime.min.time()),
                                'dateTo':datetime.combine(dateTo, datetime.min.time()), 'active': True}
                reservations.insert_one(newReservation)
                sector['availableLength']=sector['availableLength']-dimensions[y_id]['length']
                sectors_list[arrayid]= sector
                ports.update_one({'_id':portInstance},{'$set':{'sectors':sectors_list}})
            else:
                newReservation ={'reservationNumber':reservationNumber,'portID': port_id, 'sectorID': sector_name,
                                 'type': sector_type, 'slot': slot_id,
                                 'ownerName':name,'ownerSurname':surname, 'yachtID': yachtID,
                                 'dateFrom':datetime.combine(dateFrom, datetime.min.time()),
                                 'dateTo':datetime.combine(dateTo, datetime.min.time()), 'active': True}
                reservations.insert_one(newReservation)
                wantedSlot=None
                slot_list=sector['slots']
                for slot in sector['slots']:
                    if slot['id']==slot_id:
                        wantedSlot=slot
                if wantedSlot!=None:
                    wantedSlot['taken']=True
                slot_list[slot_id]=wantedSlot
                sector['slots']=slot_list
                sectors_list[arrayid]=sector
                ports.update_one({'_id': portInstance}, {'$set': {'sectors': sectors_list}})
            return render(request, 'GdzieTaKeja/results.html', {'reservationNumber':reservationNumber, 'action': 'reserve'})
    else:
        form = DataForm()
    return render(request, 'GdzieTaKeja/reserve.html', {'port_id':port_id,'dim_len':len(dimensions), 'port':port,
                                                        'sector_name':sector_name, 'sector_type':sector_type,
                                                        'slot_id':slot_id, 'form':form,'y_id':y_id})

def reservation(request):
    reservations_found = None
    if request.method == 'POST':
        form = ReservationForm(request.POST)
        if form.is_valid():
            reservationNumberInput = form.cleaned_data['reservationNumber']

            reservations_found = reservations.find({'reservationNumber': reservationNumberInput})

            return render(request,'GdzieTaKeja/reservations.html', {'form': form,'reservation_found':reservations_found})

    else:
        form = ReservationForm()
    return render(request,'GdzieTaKeja/reservations.html',{'form':form,'reservation_found':reservations_found})

def edit_reservation(request, reservation_number):
    reservation = reservations.find_one({'reservationNumber': reservation_number})
    if request.method == 'POST':
        form = EditReservationForm(request.POST)
        if request.POST['modify'] == 'Edytuj':
            if form.is_valid():
                beforeDateFrom=reservation['dateFrom']
                beforeDateTo=reservation['dateTo']
                dateFrom=form.cleaned_data['dateFrom']
                dateTo=form.cleaned_data['dateTo']
                reservations.update_one({'reservationNumber': reservation_number},
                                        {'$set': {'dateFrom': datetime.combine(dateFrom, datetime.min.time()),
                                                                    'dateTo':datetime.combine(dateTo, datetime.min.time())}})
                return render(request, 'GdzieTaKeja/results.html', {'action': 'modify',
                                                                 'beforeF':beforeDateFrom,'beforeT':beforeDateTo,
                                                                 "dateFrom":dateFrom,'dateTo':dateTo})
        elif request.POST['modify'] == 'Usuń':
            portInstance=ObjectId(reservation['portID'])
            port=ports.find_one({'_id':portInstance})
            sectors_list=port['sectors']
            sectorToUpdate = None
            arrayid = -1
            for i in range(len(sectors_list)):

GdzieTaKeja/templates/GdzieTaKeja/edit_reservation.html
<!doctype html>
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static '/GdzieTaKeja/editreservation_style.css' %}">
<body>
    <div class="navbar">
        <a id="curr" href="{% url 'GdzieTaKeja:ports' %}"><div class="logo">GdzieTaKeja</div></a>
        <div class="options">
            <a id="curr" href="{% url 'GdzieTaKeja:ports' %}"><div id="opt">Przystanie</div></a>
            <a id="curr" href="{% url 'GdzieTaKeja:reservation' %}"><div id="opt">Rezerwacje</div></a>
        </div>
    </div>
    <div class="container">
         <h1 id="listheader">EDYTUJ REZERWACJĘ</h1>
         <div class="cityform">
             <form action='' method="POST">
                 {% csrf_token %}
                 {{ form }}
                 <br>
                 <input class="submitButton" type="submit" name='modify' value="Edytuj">
                 <input class="submitButton" type="submit" name='modify' value="Usuń">
                 <input class="submitButton" type="submit" name='modify' value="Cofnij">
             </form>
         </div>
    </div>
</body>

GdzieTaKeja/templates/GdzieTaKeja/editreservation.html
<!doctype html>
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static '/GdzieTaKeja/editreservation_style.css' %}">
<body>
    <div class="navbar">
        <a id="curr" href="{% url 'GdzieTaKeja:ports' %}"><div class="logo">GdzieTaKeja</div></a>
        <div class="options">
            <a id="curr" href="{% url 'GdzieTaKeja:ports' %}"><div id="opt">Przystanie</div></a>
            <a id="curr" href="{% url 'GdzieTaKeja:reservation' %}"><div id="opt">Rezerwacje</div></a>
        </div>
    </div>
    <div class="container">
         <h1 id="listheader">EDYTUJ REZERWACJĘ</h1>
         <div class="cityform">
             <form action='' method="POST">
                 {% csrf_token %}
                 {{ form }}
                 <br>
                 <input class="submitButton" type="submit" name='modify' value="Edytuj">
                 <input class="submitButton" type="submit" name='modify' value="Usuń">
                 <input class="submitButton" type="submit" name='modify' value="Cofnij">
             </form>
         </div>
    </div>
</body>

GdzieTaKeja/templates/GdzieTaKeja/ports.html
<!doctype html>
{% load static %}
{% load GdzieTaKeja_tags %}
<link rel="stylesheet" type="text/css" href="{% static '/GdzieTaKeja/port_style.css' %}">
<body>
    <div class="navbar">
        <a id="curr" href="{% url 'GdzieTaKeja:ports' %}"><div class="logo">GdzieTaKeja</div></a>
        <div class="options">
            <a id="curr" href="{% url 'GdzieTaKeja:ports' %}"><div id="opt">Przystanie</div></a>
            <a id="curr" href="{% url 'GdzieTaKeja:reservation' %}"><div id="opt">Rezerwacje</div></a>
        </div>

    </div>

    <div class="container">
        <h1 id="listheader">PRZYSTANIE</h1>
        <div class="cityform">
            <form action='' method="POST">
                {% csrf_token %}
                <div class="dimtable">{{ form.as_table }}</div>

                <input class="submitButton" type="submit" value="Szukaj">
            </form>
        </div>
        <div class="portlist">
            {% for port in port_list %}
                <a id="link" href="{% url 'GdzieTaKeja:sectors' port_id=port|mongo_id %}">
                    <div class="portCard">
                        <p>{{ port.name }}</p>
                    </div>
                </a>
            {% endfor %}
        </div>

    </div>
</body>

GdzieTaKeja/templates/GdzieTaKeja/reservations.html
<!doctype html>
{% load static %}
{% load GdzieTaKeja_tags %}
<link rel="stylesheet" type="text/css" href="{% static '/GdzieTaKeja/reservation_style.css' %}">
<body>
    <div class="navbar">
        <a id="curr" href="{% url 'GdzieTaKeja:ports' %}"><div class="logo">GdzieTaKeja</div></a>
        <div class="options">
            <a id="curr" href="{% url 'GdzieTaKeja:ports' %}"><div id="opt">Przystanie</div></a>
            <a id="curr" href="{% url 'GdzieTaKeja:reservation' %}"><div id="opt">Rezerwacje</div></a>
        </div>

    </div>
    <div class="container">
         <h1 id="listheader">Wyszukaj swoją rezerwację:</h1>
         <div class="cityform">
             <form action='' method="POST">

                {% csrf_token %}
                <div class = "dimtable">{{ form.as_table }}</div>
                <input class="submitButton" type="submit" value="Szukaj">

             </form>
         </div>
        <div class="portlist">
            {% for res in reservation_found %}
                {% if res.active == True %}
                    <a id="link" href="{% url 'GdzieTaKeja:edit_reservation' reservation_number=res.reservationNumber %}">
                        <div class="portCardAct">
                            <p>Numer rezerwacji: {{ res.reservationNumber }}</p>
                            <p class="reservationStatus" style="color: limegreen">Rezerwacja aktywna</p>
                        </div>
                    </a>
                {% else %}
                    <div id = "link">
                        <div class="portCard">
                            <p>Numer rezerwacji: {{ res.reservationNumber }}</p>
                            <p class="reservationStatus" style="color: red">Rezerwacja nieaktywna/anulowana</p>
                        </div>
                    </div>
                {% endif %}
            {% endfor %}
        </div>
    </div>
</body>

GdzieTaKeja/templates/GdzieTaKeja/reserve.html
<!doctype html>
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static '/GdzieTaKeja/reserve_style.css' %}">
<body>
    <div class="container">
        {% if sector_type == "parallel" %}
            <h1 id="listheader">Rezerwacja: </h1>
            <div class = "portSektor">port: {{ port.name }}</div>
            <div class = "portSektor">sektor: {{ sector_name }}</div>
            <div class="act-opt">
                <a id="link" href="{% url 'GdzieTaKeja:ports' %}"><div id="go_back">Anuluj rezerwację</div></a>
                <a id="link" href="{% url 'GdzieTaKeja:sectors' port_id=port_id %}"><div id="go_back">Wróć do sektorów</div></a>
            </div>
        {% else %}
            <h1 id="listheader">Rezerwacja: </h1>
            <div class = "portSektor">port: {{ port.name }}</div>
            <div class = "portSektor">sektor: {{ sector_name }}</div>
            <div class = "portSektor">slot: {{ slot_id }}</div>
           <div class="act-opt">
                <a id="link" href="{% url 'GdzieTaKeja:ports' %}"><div id="go_back">Anuluj rezerwację</div></a>
                <a id="link" href="{% url 'GdzieTaKeja:slots' port_id=port_id sector_name=sector_name y_id=y_id%}"><div id="go_back">Wróć do miejsc</div></a>
            </div>
        {% endif %}
        <form action="" method="post">
            {% csrf_token %}
            <table class="dimtable">{{ form.as_table }}</table>
            <input class="submitButton" type="submit" value="Zarezerwuj">
        </form>
    </div>
</body>

GdzieTaKeja/templates/GdzieTaKeja/results.html
<!doctype html>
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static '/GdzieTaKeja/results_style.css' %}">
<body>
    <div class="container">
        {% if action == 'reserve' %}
            <h1 id="listheader">Dziękujemy za rezerwację w naszej Marinie!</h1><br>
            <div>Numer twojej rezerwacji to: <div id="resNumber">{{ reservationNumber }}</div></div><br>
            <div> Proszę zapamiętać numer rezerwacji przed kontynuowaniem!</div>
        {% elif action == 'modify' %}
            <h1 id="listheader">
                Modifykacja rezerwacji powiodła się!
            </h1>
            <h1>Wprowadzone zmiany:</h1>
            {% if beforeF.date != dateFrom %}
                <p style="font-size: 20px">Data rozpoczęcia rezerwacji: {{ beforeF.date}} ➡ {{ dateFrom }}</p>
            {% endif %}
            {% if beforeT.date != dateTo %}
                <p style="font-size: 20px">Data zakończenia rezerwacji: {{ beforeT.date }} ➡ {{ dateTo }}</p>
            {% endif %}
        {% elif action == 'delete' %}
            <h1>Rezerwacja została usunięta!</h1>
        {% elif action == 'reservation_unavailable' %}
            <h1>To miejsce zostało już zajęte lub wyłączone z użytku!</h1>
        {% endif %}
        <a id="link" href="{% url 'GdzieTaKeja:ports'  %}"><input class="submitButton" type="submit" value="Powrót"></a>
    </div>
</body>

GdzieTaKeja/templates/GdzieTaKeja/sectors.html
<!doctype html>
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static '/GdzieTaKeja/sector_style.css' %}">
<body>
    <div class="container">
        <h1 id="listheader">SEKTORY</h1>
        <a id="link" href="{% url 'GdzieTaKeja:ports'%}">
            <div id="go_back">Cofnij</div>
        </a>
        <form action='' method="POST">
            {% csrf_token %}
            <table class="dimtable">{{ form.as_table }}</table>
            <input class="submitButton" type="submit" value="Szukaj">
        </form>

        <div class="portlist">
                {% for sector in filtered_sectors %}
                    {% if sector.type == "perpendicular" %}
                        <a id="link" href="{% url 'GdzieTaKeja:slots' port_id=port_id sector_name=sector.name y_id=y_id %}">
                            <div class="portCard">
                                <p>Typ sektora: {{ sector.name }}</p>
                            </div>
                        </a>
                    {% else %}
                        <a id="link" href="{% url 'GdzieTaKeja:reserve' port_id=port_id sector_name=sector.name y_id=y_id slot_id=0 %}">
                            <div class="portCard">
                                <p>Typ sektora: {{ sector.name }}</p>
                            </div>
                        </a>
                    {% endif %}
                {% endfor %}
        </div>
    </div>
</body>

GdzieTaKeja/templates/GdzieTaKeja/slots.html
<!doctype html>
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static '/GdzieTaKeja/slot_style.css' %}">
<body>
    <div class="container">
        <div class="portHeader">Miejsca w porcie: {{port.name}}</div>
        <div class="sectorHeader">W sektorze: {{ sector_name }}</div>
        <a id="link" href="{% url 'GdzieTaKeja:sectors' port_id%}"><div id="go_back">Cofnij</div></a>
        <div class="portlist">
            {% for slot in slot_list %}
               <a id="link" href="{% url 'GdzieTaKeja:reserve' port_id=port_id sector_name=sector_name slot_id=slot.id y_id=y_id %}">
                  <div class="portCard">
                      <p>Numer miejsca: {{ slot.id }}</p>
                  </div>
               </a>
            {% endfor %}
        </div>
    </div>
</body>

GdzieTaKeja/templates/GdzieTaKeja/thanks.html
<!doctype html>
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static '/GdzieTaKeja/results_style.css' %}">
<body>
    <div class="container">
        {% if action == 'reserve' %}
            <h1 id="listheader">Dziękujemy za rezerwację w naszej Marinie!</h1><br>
            <div>Numer twojej rezerwacji to: <div id="resNumber">{{ reservationNumber }}</div></div><br>
            <div> Proszę zapamiętać numer rezerwacji przed kontynuowaniem!</div>
        {% elif action == 'modify' %}
            <h1 id="listheader">
                Modifykacja rezerwacji powiodła się!
            </h1>
            <h1>Wprowadzone zmiany:</h1>
            {% if beforeF.date != dateFrom %}
                <p style="font-size: 20px">Data rozpoczęcia rezerwacji: {{ beforeF.date}} ➡ {{ dateFrom }}</p>
            {% endif %}
            {% if beforeT.date != dateTo %}
                <p style="font-size: 20px">Data zakończenia rezerwacji: {{ beforeT.date }} ➡ {{ dateTo }}</p>
            {% endif %}
        {% elif action == 'delete' %}
            <h1>Rezerwacja została usunięta!</h1>
        {% elif action == 'reservation_unavailable' %}
            <h1>To miejsce zostało już zajęte lub wyłączone z użytku!</h1>
        {% endif %}
        <a id="link" href="{% url 'GdzieTaKeja:ports'  %}"><input class="submitButton" type="submit" value="Powrót"></a>
    </div>
</body>